/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iBridgeSol from "./IBridge.sol";
export type { iBridgeSol };
export type { Bridge } from "./Bridge";
export type { Token } from "./Token";
export type { TokenPeg } from "./TokenPeg";
