/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IBridgeReceiver,
  IBridgeReceiverInterface,
} from "../../../contracts/IBridge.sol/IBridgeReceiver";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "source",
        type: "address",
      },
      {
        internalType: "bytes",
        name: "message",
        type: "bytes",
      },
    ],
    name: "onMessageReceived",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IBridgeReceiver__factory {
  static readonly abi = _abi;
  static createInterface(): IBridgeReceiverInterface {
    return new utils.Interface(_abi) as IBridgeReceiverInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IBridgeReceiver {
    return new Contract(address, _abi, signerOrProvider) as IBridgeReceiver;
  }
}
